# C compiler
CC = gcc
CC_FLAGS = -fopenmp -O3

feyman_omp_1: 
	$(CC) $(CC_FLAGS) feyman_omp_1.c -o feyman_omp_1 -lm

feyman_omp_2: 
	$(CC) $(CC_FLAGS) feyman_omp_2.c -o feyman_omp_2 -lm

feyman_omp_3: 
	$(CC) $(CC_FLAGS) feyman_omp_3.c -o feyman_omp_3 -lm

feyman_omp_4: 
	$(CC) $(CC_FLAGS) feyman_omp_4.c -o feyman_omp_4 -lm

clean:
	rm -f feyman_omp_1 feyman_omp_2 feyman_omp_3 feyman_omp_4 
